from pyspark.sql import SparkSession
from pyspark.sql.context import HiveContext
from pyspark.sql.functions import *
from pyspark.sql.types import *
import pyspark.sql.functions as F
from functools import reduce
from datetime import datetime, timedelta
from pyspark.sql.functions import monotonically_increasing_id,row_number
from pyspark.sql.window import Window 
cur_date = (datetime.now()).strftime('%Y-%m-%d')
cur_time = (datetime.now()).strftime('%Y-%m-%d %H:%M:%S')

# Create spark session with hive enabled
spark = SparkSession \
    .builder \
    .appName("SparkByExamples.com") \
    .config("spark.sql.warehouse.dir", "/user/hive/warehouse") \
    .config("spark.sql.catalogImplementation", "hive") \
    .enableHiveSupport() \
    .getOrCreate()

hv = HiveContext(spark)
start_date = datetime.now() + timedelta(hours=7)
run_date = datetime.now().strftime('%Y%m%d%H%M%S')

#==========================> READ DATA
#hv.sql('CREATE TABLE IF NOT EXISTS base.chg_sa_product(trx_date string,rkey string,mapping_key_type string,service_type string,l1_name string,l2_name string,l3_name string,l4_name string,price string,updated_date string,product_name string,plan_type string,plan_service string,quota_value string,quota_unit string,validity_value string,validity_unit string,vascode_type string,file_id string,load_ts string,load_user string) STORED AS PARQUET;')
#spark.read.parquet('file:///home/hdoop/datayunita/USAGECHG/SA_Product/*').write.mode('overwrite').saveAsTable("base.chg_sa_product")

hv.sql('CREATE TABLE IF NOT EXISTS base.chg_SAProdline(product_name string,price string,l1 string,l2 string,l3 string,l4 string,note string,source string)row format delimited fields terminated by "|"')
hv.sql("load data local inpath 'file:///home/hdoop/datayunita/USAGECHG/SA_PRODLINE_BONUS/*' overwrite into table base.chg_SAProdline;")


# READ SA_PRODUCT
df_SAproduct = hv.table('base.chg_sa_product')\
                .select('rkey','mapping_key_type','service_type','l1_name','l2_name','l3_name','l4_name','price','updated_date','product_name','plan_type','plan_service','quota_value','quota_unit','validity_value','validity_unit','vascode_type')

# READ SA_PRODLINE
df_SAProdline = hv.table('base.chg_SAProdline')\
                .withColumn('substr_l4', substring((trim(col('l4'))), 4,8))

# READ SA_USAGE_CHG_Part1
df_CHG_Part1 = hv.table('output.sa_usage_chg1').toDF('timestamp_r','trx_date','trx_hour','a_party','account_owner','msisdn','subs_id','cust_type_desc','cust_subtype_desc','location_number_type_a','location_number_a','b_party','location_number_type_b','location_number_b','number_of_reroutings','imsi','number_of_network_reroutings','redirecting_party_id','pre_call_duration','call_duration','chargingid','roaming_flag','vlr_num','cell_id','lacci_id','lacci_closing_flag','lac','ci','node_type','area_sales','region_sales','branch','subbranch','cluster_sales','provinsi','kabupaten','kecamatan','kelurahan','negotiated_qos','requested_qos','subscribed_qos','dialled_apn','event_type','provider_id','currency','subscriber_status','forwarding_flag','first_call_flag','camel_roaming','time_zone','account_balance','account_number','event_source','guiding_resource_type','rounded_duration','total_volume','rounded_total_volume','event_start_period','cifa','account_delta','bonus_consumed','credit_indicator','rev','discount_amount','free_total_volume','free_duration','call_direction','charge_code','special_number_ind','bonus_information','internal_cause','basic_cause','time_band','call_type','vas_code','service_filter','national_calling_zone','national_called_zone','international_calling_zone','international_called_zone','event_id','access_code','country_name','cp_name','content_id','rating_group','bft_indicator','unapplied_amount','partition_id','rated_date_time','area','cost_band','rating_offer_id','settlement_indicator','tap_code','mcc_mnc','rating_pricing_item_id','file_identifier','record_number','future_string1','future_string2','future_string3','allowance_consumed_revenue','ifrs_ind_for_allowance_revenue','ifrs_ind_for_vas_event','itemized_bill_fee','consumed_monetary_allowance','partial_charge_ind','brand','offer_id','file_id','load_ts','load_user','site_name','pre_post_flag','mcc','mnc','network_activity_id','filename','rec_id','event_date','productline_bonus_l4','retry_count','retry_ts','status_data','status','trx_lacci')\
                    .withColumn('service', 
                              F.when((F.col("service_filter").startswith("1_")), "s1")
                               .when((F.col("service_filter").startswith("2_")), "s2")
                               .when((F.col("service_filter").startswith("3_")), "s3")
                               .when((F.col("service_filter").startswith("5_")), "s5")
                                  .otherwise("sR"))
# CEK
print("kolom chg part1=",df_CHG_Part1.count())

# SPLIT FILTER
df_Filter1 = df_CHG_Part1.filter(F.col("service").startswith("s1"))
df_Filter2 = df_CHG_Part1.filter(F.col("service").startswith("s2"))
df_Filter3 = df_CHG_Part1.filter(F.col("service").startswith("s3"))
df_Filter5 = df_CHG_Part1.filter(F.col("service").startswith("s5"))
df_FilterR = df_CHG_Part1.filter(F.col("service").startswith("sR"))


# JOIN OFFER_ID to proses service_filter 1
df_ServiceFilter1 = df_Filter1.join(df_SAproduct,df_Filter1.offer_id ==  df_SAproduct.rkey, how = 'left')\
                            .withColumn('l4_name', 
                              F.when((F.col('offer_id') == F.col('rkey')) & (F.col('mapping_key_type').isNull()), F.col('l4_name'))
                                  .otherwise("NQ"))\
                            .withColumn('l3_name', 
                              F.when((F.col('offer_id') == F.col('rkey')) & (F.col('mapping_key_type').isNull()), F.col('l3_name'))
                                  .otherwise("NQ"))\
                            .withColumn('l2_name', 
                              F.when((F.col('offer_id') == F.col('rkey')) & (F.col('mapping_key_type').isNull()), F.col('l2_name'))
                                  .otherwise("NQ"))\
                            .withColumn('l1_name', 
                              F.when((F.col('offer_id') == F.col('rkey')) & (F.col('mapping_key_type').isNull()), F.col('l1_name'))
                                  .otherwise("NQ"))\
                            .select('timestamp_r','trx_date','trx_hour','a_party','account_owner','msisdn','subs_id','cust_type_desc','cust_subtype_desc','location_number_type_a','location_number_a','b_party','location_number_type_b','location_number_b','number_of_reroutings','imsi','number_of_network_reroutings','redirecting_party_id','pre_call_duration','call_duration','chargingid','roaming_flag','vlr_num','cell_id','lacci_id','lacci_closing_flag','lac','ci','node_type','area_sales','region_sales','branch','subbranch','cluster_sales','provinsi','kabupaten','kecamatan','kelurahan','negotiated_qos','requested_qos','subscribed_qos','dialled_apn','event_type','provider_id','currency','subscriber_status','forwarding_flag','first_call_flag','camel_roaming','time_zone','account_balance','account_number','event_source','guiding_resource_type','rounded_duration','total_volume','rounded_total_volume','event_start_period','cifa','account_delta','bonus_consumed','credit_indicator','rev','discount_amount','free_total_volume','free_duration','call_direction','charge_code','special_number_ind','bonus_information','internal_cause','basic_cause','time_band','call_type','vas_code','service_filter','national_calling_zone','national_called_zone','international_calling_zone','international_called_zone','event_id','access_code','country_name','cp_name','content_id','rating_group','bft_indicator','unapplied_amount','partition_id','rated_date_time','area','cost_band','l4_name','l3_name','l2_name','l1_name','rating_offer_id','settlement_indicator','tap_code','mcc_mnc','rating_pricing_item_id','file_identifier','record_number','future_string1','future_string2','future_string3','allowance_consumed_revenue','ifrs_ind_for_allowance_revenue','ifrs_ind_for_vas_event','itemized_bill_fee','consumed_monetary_allowance','partial_charge_ind','brand','offer_id','file_id','load_ts','load_user','site_name','pre_post_flag','mcc','mnc','network_activity_id','filename','rec_id','event_date','productline_bonus_l4','retry_count','retry_ts','status_data','status','trx_lacci')

# JOIN  B_PARTY to proses service_filter 2
df_ServiceFilter2 = df_Filter2.join(df_SAproduct,df_Filter2.b_party ==  df_SAproduct.rkey, how = 'left')\
                            .withColumn('l4_name', 
                                F.when((F.col('b_party') == F.col('rkey')) & (F.col('service_type') == "2_") & (F.col('product_name').isNull()), F.col('l4_name'))
                                    .otherwise("NQ"))\
                            .withColumn('l3_name', 
                                F.when((F.col('b_party') == F.col('rkey')) & (F.col('service_type') == "2_") & (F.col('product_name').isNull()), F.col('l3_name'))
                                    .otherwise("NQ"))\
                            .withColumn('l2_name', 
                                F.when((F.col('b_party') == F.col('rkey')) & (F.col('service_type') == "2_") & (F.col('product_name').isNull()), F.col('l2_name'))
                                    .otherwise("NQ"))\
                            .withColumn('l1_name', 
                                F.when((F.col('b_party') == F.col('rkey')) & (F.col('service_type') == "2_") & (F.col('product_name').isNull()), F.col('l1_name'))
                                    .otherwise("NQ"))\
                            .select('timestamp_r','trx_date','trx_hour','a_party','account_owner','msisdn','subs_id','cust_type_desc','cust_subtype_desc','location_number_type_a','location_number_a','b_party','location_number_type_b','location_number_b','number_of_reroutings','imsi','number_of_network_reroutings','redirecting_party_id','pre_call_duration','call_duration','chargingid','roaming_flag','vlr_num','cell_id','lacci_id','lacci_closing_flag','lac','ci','node_type','area_sales','region_sales','branch','subbranch','cluster_sales','provinsi','kabupaten','kecamatan','kelurahan','negotiated_qos','requested_qos','subscribed_qos','dialled_apn','event_type','provider_id','currency','subscriber_status','forwarding_flag','first_call_flag','camel_roaming','time_zone','account_balance','account_number','event_source','guiding_resource_type','rounded_duration','total_volume','rounded_total_volume','event_start_period','cifa','account_delta','bonus_consumed','credit_indicator','rev','discount_amount','free_total_volume','free_duration','call_direction','charge_code','special_number_ind','bonus_information','internal_cause','basic_cause','time_band','call_type','vas_code','service_filter','national_calling_zone','national_called_zone','international_calling_zone','international_called_zone','event_id','access_code','country_name','cp_name','content_id','rating_group','bft_indicator','unapplied_amount','partition_id','rated_date_time','area','cost_band','l4_name','l3_name','l2_name','l1_name','rating_offer_id','settlement_indicator','tap_code','mcc_mnc','rating_pricing_item_id','file_identifier','record_number','future_string1','future_string2','future_string3','allowance_consumed_revenue','ifrs_ind_for_allowance_revenue','ifrs_ind_for_vas_event','itemized_bill_fee','consumed_monetary_allowance','partial_charge_ind','brand','offer_id','file_id','load_ts','load_user','site_name','pre_post_flag','mcc','mnc','network_activity_id','filename','rec_id','event_date','productline_bonus_l4','retry_count','retry_ts','status_data','status','trx_lacci')\
                            .toDF('timestamp_r','trx_date','trx_hour','a_party','account_owner','msisdn','subs_id','cust_type_desc','cust_subtype_desc','location_number_type_a','location_number_a','b_party','location_number_type_b','location_number_b','number_of_reroutings','imsi','number_of_network_reroutings','redirecting_party_id','pre_call_duration','call_duration','chargingid','roaming_flag','vlr_num','cell_id','lacci_id','lacci_closing_flag','lac','ci','node_type','area_sales','region_sales','branch','subbranch','cluster_sales','provinsi','kabupaten','kecamatan','kelurahan','negotiated_qos','requested_qos','subscribed_qos','dialled_apn','event_type','provider_id','currency','subscriber_status','forwarding_flag','first_call_flag','camel_roaming','time_zone','account_balance','account_number','event_source','guiding_resource_type','rounded_duration','total_volume','rounded_total_volume','event_start_period','cifa','account_delta','bonus_consumed','credit_indicator','rev','discount_amount','free_total_volume','free_duration','call_direction','charge_code','special_number_ind','bonus_information','internal_cause','basic_cause','time_band','call_type','vas_code','service_filter','national_calling_zone','national_called_zone','international_calling_zone','international_called_zone','event_id','access_code','country_name','cp_name','content_id','rating_group','bft_indicator','unapplied_amount','partition_id','rated_date_time','area','cost_band','l4_name_x','l3_name_x','l2_name_x','l1_name_x','rating_offer_id','settlement_indicator','tap_code','mcc_mnc','rating_pricing_item_id','file_identifier','record_number','future_string1','future_string2','future_string3','allowance_consumed_revenue','ifrs_ind_for_allowance_revenue','ifrs_ind_for_vas_event','itemized_bill_fee','consumed_monetary_allowance','partial_charge_ind','brand','offer_id','file_id','load_ts','load_user','site_name','pre_post_flag','mcc','mnc','network_activity_id','filename','rec_id','event_date','productline_bonus_l4','retry_count','retry_ts','status_data','status','trx_lacci')\
                            .join(df_SAproduct,col('offer_id') == col('rkey'), how = 'left')\
                            .withColumn('l4_name', 
                                F.when((F.col('l4_name_x') == "NQ") & (F.col('offer_id') == F.col('rkey')) & (F.col('service_type') == "2_") & (F.col('product_name').isNull()), F.col('l4_name'))
                                    .otherwise(F.col('l4_name_x')))\
                            .withColumn('l3_name', 
                                F.when((F.col('l3_name_x') == "NQ") & (F.col('offer_id') == F.col('rkey')) & (F.col('service_type') == "2_") & (F.col('product_name').isNull()), F.col('l3_name'))
                                    .otherwise(F.col('l3_name_x')))\
                            .withColumn('l2_name', 
                                F.when((F.col('l2_name_x') == "NQ") & (F.col('offer_id') == F.col('rkey')) & (F.col('service_type') == "2_") & (F.col('product_name').isNull()), F.col('l2_name'))
                                    .otherwise(F.col('l2_name_x')))\
                            .withColumn('l1_name', 
                                F.when((F.col('l1_name_x') == "NQ") & (F.col('offer_id') == F.col('rkey')) & (F.col('service_type') == "2_") & (F.col('product_name').isNull()), F.col('l1_name'))
                                    .otherwise(F.col('l1_name_x')))\
                            .select('timestamp_r','trx_date','trx_hour','a_party','account_owner','msisdn','subs_id','cust_type_desc','cust_subtype_desc','location_number_type_a','location_number_a','b_party','location_number_type_b','location_number_b','number_of_reroutings','imsi','number_of_network_reroutings','redirecting_party_id','pre_call_duration','call_duration','chargingid','roaming_flag','vlr_num','cell_id','lacci_id','lacci_closing_flag','lac','ci','node_type','area_sales','region_sales','branch','subbranch','cluster_sales','provinsi','kabupaten','kecamatan','kelurahan','negotiated_qos','requested_qos','subscribed_qos','dialled_apn','event_type','provider_id','currency','subscriber_status','forwarding_flag','first_call_flag','camel_roaming','time_zone','account_balance','account_number','event_source','guiding_resource_type','rounded_duration','total_volume','rounded_total_volume','event_start_period','cifa','account_delta','bonus_consumed','credit_indicator','rev','discount_amount','free_total_volume','free_duration','call_direction','charge_code','special_number_ind','bonus_information','internal_cause','basic_cause','time_band','call_type','vas_code','service_filter','national_calling_zone','national_called_zone','international_calling_zone','international_called_zone','event_id','access_code','country_name','cp_name','content_id','rating_group','bft_indicator','unapplied_amount','partition_id','rated_date_time','area','cost_band','l4_name','l3_name','l2_name','l1_name','rating_offer_id','settlement_indicator','tap_code','mcc_mnc','rating_pricing_item_id','file_identifier','record_number','future_string1','future_string2','future_string3','allowance_consumed_revenue','ifrs_ind_for_allowance_revenue','ifrs_ind_for_vas_event','itemized_bill_fee','consumed_monetary_allowance','partial_charge_ind','brand','offer_id','file_id','load_ts','load_user','site_name','pre_post_flag','mcc','mnc','network_activity_id','filename','rec_id','event_date','productline_bonus_l4','retry_count','retry_ts','status_data','status','trx_lacci')\
                            .toDF('timestamp_r','trx_date','trx_hour','a_party','account_owner','msisdn','subs_id','cust_type_desc','cust_subtype_desc','location_number_type_a','location_number_a','b_party','location_number_type_b','location_number_b','number_of_reroutings','imsi','number_of_network_reroutings','redirecting_party_id','pre_call_duration','call_duration','chargingid','roaming_flag','vlr_num','cell_id','lacci_id','lacci_closing_flag','lac','ci','node_type','area_sales','region_sales','branch','subbranch','cluster_sales','provinsi','kabupaten','kecamatan','kelurahan','negotiated_qos','requested_qos','subscribed_qos','dialled_apn','event_type','provider_id','currency','subscriber_status','forwarding_flag','first_call_flag','camel_roaming','time_zone','account_balance','account_number','event_source','guiding_resource_type','rounded_duration','total_volume','rounded_total_volume','event_start_period','cifa','account_delta','bonus_consumed','credit_indicator','rev','discount_amount','free_total_volume','free_duration','call_direction','charge_code','special_number_ind','bonus_information','internal_cause','basic_cause','time_band','call_type','vas_code','service_filter','national_calling_zone','national_called_zone','international_calling_zone','international_called_zone','event_id','access_code','country_name','cp_name','content_id','rating_group','bft_indicator','unapplied_amount','partition_id','rated_date_time','area','cost_band','l4_name_x','l3_name_x','l2_name_x','l1_name_x','rating_offer_id','settlement_indicator','tap_code','mcc_mnc','rating_pricing_item_id','file_identifier','record_number','future_string1','future_string2','future_string3','allowance_consumed_revenue','ifrs_ind_for_allowance_revenue','ifrs_ind_for_vas_event','itemized_bill_fee','consumed_monetary_allowance','partial_charge_ind','brand','offer_id','file_id','load_ts','load_user','site_name','pre_post_flag','mcc','mnc','network_activity_id','filename','rec_id','event_date','productline_bonus_l4','retry_count','retry_ts','status_data','status','trx_lacci')\
                            .join(df_SAproduct,col('service_filter') == col('rkey'), how = 'left')\
                            .withColumn('l4_name', 
                                F.when((F.col('l4_name_x') == "NQ") & (F.col('service_filter') == F.col('rkey')) & (F.col('service_type') == "2_") & (F.col('product_name').isNull()), F.col('l4_name'))
                                    .otherwise(F.col('l4_name_x')))\
                            .withColumn('l3_name', 
                                F.when((F.col('l3_name_x') == "NQ") & (F.col('service_filter') == F.col('rkey')) & (F.col('service_type') == "2_") & (F.col('product_name').isNull()), F.col('l3_name'))
                                    .otherwise(F.col('l3_name_x')))\
                            .withColumn('l2_name', 
                                F.when((F.col('l2_name_x') == "NQ") & (F.col('service_filter') == F.col('rkey')) & (F.col('service_type') == "2_") & (F.col('product_name').isNull()), F.col('l2_name'))
                                    .otherwise(F.col('l2_name_x')))\
                            .withColumn('l1_name', 
                                F.when((F.col('l1_name_x') == "NQ") & (F.col('service_filter') == F.col('rkey')) & (F.col('service_type') == "2_") & (F.col('product_name').isNull()), F.col('l1_name'))
                                    .otherwise(F.col('l1_name_x')))\
                            .select('timestamp_r','trx_date','trx_hour','a_party','account_owner','msisdn','subs_id','cust_type_desc','cust_subtype_desc','location_number_type_a','location_number_a','b_party','location_number_type_b','location_number_b','number_of_reroutings','imsi','number_of_network_reroutings','redirecting_party_id','pre_call_duration','call_duration','chargingid','roaming_flag','vlr_num','cell_id','lacci_id','lacci_closing_flag','lac','ci','node_type','area_sales','region_sales','branch','subbranch','cluster_sales','provinsi','kabupaten','kecamatan','kelurahan','negotiated_qos','requested_qos','subscribed_qos','dialled_apn','event_type','provider_id','currency','subscriber_status','forwarding_flag','first_call_flag','camel_roaming','time_zone','account_balance','account_number','event_source','guiding_resource_type','rounded_duration','total_volume','rounded_total_volume','event_start_period','cifa','account_delta','bonus_consumed','credit_indicator','rev','discount_amount','free_total_volume','free_duration','call_direction','charge_code','special_number_ind','bonus_information','internal_cause','basic_cause','time_band','call_type','vas_code','service_filter','national_calling_zone','national_called_zone','international_calling_zone','international_called_zone','event_id','access_code','country_name','cp_name','content_id','rating_group','bft_indicator','unapplied_amount','partition_id','rated_date_time','area','cost_band','l4_name','l3_name','l2_name','l1_name','rating_offer_id','settlement_indicator','tap_code','mcc_mnc','rating_pricing_item_id','file_identifier','record_number','future_string1','future_string2','future_string3','allowance_consumed_revenue','ifrs_ind_for_allowance_revenue','ifrs_ind_for_vas_event','itemized_bill_fee','consumed_monetary_allowance','partial_charge_ind','brand','offer_id','file_id','load_ts','load_user','site_name','pre_post_flag','mcc','mnc','network_activity_id','filename','rec_id','event_date','productline_bonus_l4','retry_count','retry_ts','status_data','status','trx_lacci')


# JOIN  B_PARTY to proses service_filter 3
df_ServiceFilter3 = df_Filter3.join(df_SAproduct.dropDuplicates(['rkey']),df_Filter3.b_party ==  df_SAproduct.rkey, how = 'left')\
                            .withColumn('l4_name', 
                                F.when((F.col('b_party') == F.col('rkey')) & (F.col('service_type') == "3_") & (F.col('product_name').isNull()), F.col('l4_name'))
                                    .otherwise("NQ"))\
                            .withColumn('l3_name', 
                                F.when((F.col('b_party') == F.col('rkey')) & (F.col('service_type') == "3_") & (F.col('product_name').isNull()), F.col('l3_name'))
                                    .otherwise("NQ"))\
                            .withColumn('l2_name', 
                                F.when((F.col('b_party') == F.col('rkey')) & (F.col('service_type') == "3_") & (F.col('product_name').isNull()), F.col('l2_name'))
                                    .otherwise("NQ"))\
                            .withColumn('l1_name', 
                                F.when((F.col('b_party') == F.col('rkey')) & (F.col('service_type') == "3_") & (F.col('product_name').isNull()), F.col('l1_name'))
                                    .otherwise("NQ"))\
                            .select('timestamp_r','trx_date','trx_hour','a_party','account_owner','msisdn','subs_id','cust_type_desc','cust_subtype_desc','location_number_type_a','location_number_a','b_party','location_number_type_b','location_number_b','number_of_reroutings','imsi','number_of_network_reroutings','redirecting_party_id','pre_call_duration','call_duration','chargingid','roaming_flag','vlr_num','cell_id','lacci_id','lacci_closing_flag','lac','ci','node_type','area_sales','region_sales','branch','subbranch','cluster_sales','provinsi','kabupaten','kecamatan','kelurahan','negotiated_qos','requested_qos','subscribed_qos','dialled_apn','event_type','provider_id','currency','subscriber_status','forwarding_flag','first_call_flag','camel_roaming','time_zone','account_balance','account_number','event_source','guiding_resource_type','rounded_duration','total_volume','rounded_total_volume','event_start_period','cifa','account_delta','bonus_consumed','credit_indicator','rev','discount_amount','free_total_volume','free_duration','call_direction','charge_code','special_number_ind','bonus_information','internal_cause','basic_cause','time_band','call_type','vas_code','service_filter','national_calling_zone','national_called_zone','international_calling_zone','international_called_zone','event_id','access_code','country_name','cp_name','content_id','rating_group','bft_indicator','unapplied_amount','partition_id','rated_date_time','area','cost_band','l4_name','l3_name','l2_name','l1_name','rating_offer_id','settlement_indicator','tap_code','mcc_mnc','rating_pricing_item_id','file_identifier','record_number','future_string1','future_string2','future_string3','allowance_consumed_revenue','ifrs_ind_for_allowance_revenue','ifrs_ind_for_vas_event','itemized_bill_fee','consumed_monetary_allowance','partial_charge_ind','brand','offer_id','file_id','load_ts','load_user','site_name','pre_post_flag','mcc','mnc','network_activity_id','filename','rec_id','event_date','productline_bonus_l4','retry_count','retry_ts','status_data','status','trx_lacci')\
                            .toDF('timestamp_r','trx_date','trx_hour','a_party','account_owner','msisdn','subs_id','cust_type_desc','cust_subtype_desc','location_number_type_a','location_number_a','b_party','location_number_type_b','location_number_b','number_of_reroutings','imsi','number_of_network_reroutings','redirecting_party_id','pre_call_duration','call_duration','chargingid','roaming_flag','vlr_num','cell_id','lacci_id','lacci_closing_flag','lac','ci','node_type','area_sales','region_sales','branch','subbranch','cluster_sales','provinsi','kabupaten','kecamatan','kelurahan','negotiated_qos','requested_qos','subscribed_qos','dialled_apn','event_type','provider_id','currency','subscriber_status','forwarding_flag','first_call_flag','camel_roaming','time_zone','account_balance','account_number','event_source','guiding_resource_type','rounded_duration','total_volume','rounded_total_volume','event_start_period','cifa','account_delta','bonus_consumed','credit_indicator','rev','discount_amount','free_total_volume','free_duration','call_direction','charge_code','special_number_ind','bonus_information','internal_cause','basic_cause','time_band','call_type','vas_code','service_filter','national_calling_zone','national_called_zone','international_calling_zone','international_called_zone','event_id','access_code','country_name','cp_name','content_id','rating_group','bft_indicator','unapplied_amount','partition_id','rated_date_time','area','cost_band','l4_name_x','l3_name_x','l2_name_x','l1_name_x','rating_offer_id','settlement_indicator','tap_code','mcc_mnc','rating_pricing_item_id','file_identifier','record_number','future_string1','future_string2','future_string3','allowance_consumed_revenue','ifrs_ind_for_allowance_revenue','ifrs_ind_for_vas_event','itemized_bill_fee','consumed_monetary_allowance','partial_charge_ind','brand','offer_id','file_id','load_ts','load_user','site_name','pre_post_flag','mcc','mnc','network_activity_id','filename','rec_id','event_date','productline_bonus_l4','retry_count','retry_ts','status_data','status','trx_lacci')\
                            .join(df_SAproduct.dropDuplicates(['rkey']),col('offer_id') == col('rkey'), how = 'left')\
                            .withColumn('l4_name', 
                                F.when((F.col('l4_name_x') == "NQ") & (F.col('offer_id') == F.col('rkey')) & (F.col('service_type') == "3_") & (F.col('product_name').isNull()), F.col('l4_name'))
                                    .otherwise(F.col('l4_name_x')))\
                            .withColumn('l3_name', 
                                F.when((F.col('l3_name_x') == "NQ") & (F.col('offer_id') == F.col('rkey')) & (F.col('service_type') == "3_") & (F.col('product_name').isNull()), F.col('l3_name'))
                                    .otherwise(F.col('l3_name_x')))\
                            .withColumn('l2_name', 
                                F.when((F.col('l2_name_x') == "NQ") & (F.col('offer_id') == F.col('rkey')) & (F.col('service_type') == "3_") & (F.col('product_name').isNull()), F.col('l2_name'))
                                    .otherwise(F.col('l2_name_x')))\
                            .withColumn('l1_name', 
                                F.when((F.col('l1_name_x') == "NQ") & (F.col('offer_id') == F.col('rkey')) & (F.col('service_type') == "3_") & (F.col('product_name').isNull()), F.col('l1_name'))
                                    .otherwise(F.col('l1_name_x')))\
                            .select('timestamp_r','trx_date','trx_hour','a_party','account_owner','msisdn','subs_id','cust_type_desc','cust_subtype_desc','location_number_type_a','location_number_a','b_party','location_number_type_b','location_number_b','number_of_reroutings','imsi','number_of_network_reroutings','redirecting_party_id','pre_call_duration','call_duration','chargingid','roaming_flag','vlr_num','cell_id','lacci_id','lacci_closing_flag','lac','ci','node_type','area_sales','region_sales','branch','subbranch','cluster_sales','provinsi','kabupaten','kecamatan','kelurahan','negotiated_qos','requested_qos','subscribed_qos','dialled_apn','event_type','provider_id','currency','subscriber_status','forwarding_flag','first_call_flag','camel_roaming','time_zone','account_balance','account_number','event_source','guiding_resource_type','rounded_duration','total_volume','rounded_total_volume','event_start_period','cifa','account_delta','bonus_consumed','credit_indicator','rev','discount_amount','free_total_volume','free_duration','call_direction','charge_code','special_number_ind','bonus_information','internal_cause','basic_cause','time_band','call_type','vas_code','service_filter','national_calling_zone','national_called_zone','international_calling_zone','international_called_zone','event_id','access_code','country_name','cp_name','content_id','rating_group','bft_indicator','unapplied_amount','partition_id','rated_date_time','area','cost_band','l4_name','l3_name','l2_name','l1_name','rating_offer_id','settlement_indicator','tap_code','mcc_mnc','rating_pricing_item_id','file_identifier','record_number','future_string1','future_string2','future_string3','allowance_consumed_revenue','ifrs_ind_for_allowance_revenue','ifrs_ind_for_vas_event','itemized_bill_fee','consumed_monetary_allowance','partial_charge_ind','brand','offer_id','file_id','load_ts','load_user','site_name','pre_post_flag','mcc','mnc','network_activity_id','filename','rec_id','event_date','productline_bonus_l4','retry_count','retry_ts','status_data','status','trx_lacci')\
                            .toDF('timestamp_r','trx_date','trx_hour','a_party','account_owner','msisdn','subs_id','cust_type_desc','cust_subtype_desc','location_number_type_a','location_number_a','b_party','location_number_type_b','location_number_b','number_of_reroutings','imsi','number_of_network_reroutings','redirecting_party_id','pre_call_duration','call_duration','chargingid','roaming_flag','vlr_num','cell_id','lacci_id','lacci_closing_flag','lac','ci','node_type','area_sales','region_sales','branch','subbranch','cluster_sales','provinsi','kabupaten','kecamatan','kelurahan','negotiated_qos','requested_qos','subscribed_qos','dialled_apn','event_type','provider_id','currency','subscriber_status','forwarding_flag','first_call_flag','camel_roaming','time_zone','account_balance','account_number','event_source','guiding_resource_type','rounded_duration','total_volume','rounded_total_volume','event_start_period','cifa','account_delta','bonus_consumed','credit_indicator','rev','discount_amount','free_total_volume','free_duration','call_direction','charge_code','special_number_ind','bonus_information','internal_cause','basic_cause','time_band','call_type','vas_code','service_filter','national_calling_zone','national_called_zone','international_calling_zone','international_called_zone','event_id','access_code','country_name','cp_name','content_id','rating_group','bft_indicator','unapplied_amount','partition_id','rated_date_time','area','cost_band','l4_name_x','l3_name_x','l2_name_x','l1_name_x','rating_offer_id','settlement_indicator','tap_code','mcc_mnc','rating_pricing_item_id','file_identifier','record_number','future_string1','future_string2','future_string3','allowance_consumed_revenue','ifrs_ind_for_allowance_revenue','ifrs_ind_for_vas_event','itemized_bill_fee','consumed_monetary_allowance','partial_charge_ind','brand','offer_id','file_id','load_ts','load_user','site_name','pre_post_flag','mcc','mnc','network_activity_id','filename','rec_id','event_date','productline_bonus_l4','retry_count','retry_ts','status_data','status','trx_lacci')\
                            .join(df_SAproduct,col('service_filter') == col('rkey'), how = 'left')\
                            .withColumn('l4_name', 
                                F.when((F.col('l4_name_x') == "NQ") & (F.col('service_filter') == F.col('rkey')) & (F.col('service_type') == "3_") & (F.col('product_name').isNull()), F.col('l4_name'))
                                    .otherwise(F.col('l4_name_x')))\
                            .withColumn('l3_name', 
                                F.when((F.col('l3_name_x') == "NQ") & (F.col('service_filter') == F.col('rkey')) & (F.col('service_type') == "3_") & (F.col('product_name').isNull()), F.col('l3_name'))
                                    .otherwise(F.col('l3_name_x')))\
                            .withColumn('l2_name', 
                                F.when((F.col('l2_name_x') == "NQ") & (F.col('service_filter') == F.col('rkey')) & (F.col('service_type') == "3_") & (F.col('product_name').isNull()), F.col('l2_name'))
                                    .otherwise(F.col('l2_name_x')))\
                            .withColumn('l1_name', 
                                F.when((F.col('l1_name_x') == "NQ") & (F.col('service_filter') == F.col('rkey')) & (F.col('service_type') == "3_") & (F.col('product_name').isNull()), F.col('l1_name'))
                                    .otherwise(F.col('l1_name_x')))\
                            .select('timestamp_r','trx_date','trx_hour','a_party','account_owner','msisdn','subs_id','cust_type_desc','cust_subtype_desc','location_number_type_a','location_number_a','b_party','location_number_type_b','location_number_b','number_of_reroutings','imsi','number_of_network_reroutings','redirecting_party_id','pre_call_duration','call_duration','chargingid','roaming_flag','vlr_num','cell_id','lacci_id','lacci_closing_flag','lac','ci','node_type','area_sales','region_sales','branch','subbranch','cluster_sales','provinsi','kabupaten','kecamatan','kelurahan','negotiated_qos','requested_qos','subscribed_qos','dialled_apn','event_type','provider_id','currency','subscriber_status','forwarding_flag','first_call_flag','camel_roaming','time_zone','account_balance','account_number','event_source','guiding_resource_type','rounded_duration','total_volume','rounded_total_volume','event_start_period','cifa','account_delta','bonus_consumed','credit_indicator','rev','discount_amount','free_total_volume','free_duration','call_direction','charge_code','special_number_ind','bonus_information','internal_cause','basic_cause','time_band','call_type','vas_code','service_filter','national_calling_zone','national_called_zone','international_calling_zone','international_called_zone','event_id','access_code','country_name','cp_name','content_id','rating_group','bft_indicator','unapplied_amount','partition_id','rated_date_time','area','cost_band','l4_name','l3_name','l2_name','l1_name','rating_offer_id','settlement_indicator','tap_code','mcc_mnc','rating_pricing_item_id','file_identifier','record_number','future_string1','future_string2','future_string3','allowance_consumed_revenue','ifrs_ind_for_allowance_revenue','ifrs_ind_for_vas_event','itemized_bill_fee','consumed_monetary_allowance','partial_charge_ind','brand','offer_id','file_id','load_ts','load_user','site_name','pre_post_flag','mcc','mnc','network_activity_id','filename','rec_id','event_date','productline_bonus_l4','retry_count','retry_ts','status_data','status','trx_lacci')


# JOIN SERVICE FILTER 5
df_ServiceFilter5 = df_Filter5.join(df_SAproduct,df_Filter5.vas_code ==  df_SAproduct.rkey, how = 'left')\
                            .withColumn('l4_name', 
                              F.when((F.col('vas_code') == F.col('rkey')) & (F.col('service_type') == "5_"), F.col('l4_name'))
                                  .otherwise("NQ"))\
                            .withColumn('l3_name', 
                              F.when((F.col('vas_code') == F.col('rkey')) & (F.col('service_type') == "5_"), F.col('l3_name'))
                                  .otherwise("NQ"))\
                            .withColumn('l2_name', 
                              F.when((F.col('vas_code') == F.col('rkey')) & (F.col('service_type') == "5_"), F.col('l2_name'))
                                  .otherwise("NQ"))\
                            .withColumn('l1_name', 
                              F.when((F.col('vas_code') == F.col('rkey')) & (F.col('service_type') == "5_"), F.col('l1_name'))
                                  .otherwise("NQ"))\
                            .select('timestamp_r','trx_date','trx_hour','a_party','account_owner','msisdn','subs_id','cust_type_desc','cust_subtype_desc','location_number_type_a','location_number_a','b_party','location_number_type_b','location_number_b','number_of_reroutings','imsi','number_of_network_reroutings','redirecting_party_id','pre_call_duration','call_duration','chargingid','roaming_flag','vlr_num','cell_id','lacci_id','lacci_closing_flag','lac','ci','node_type','area_sales','region_sales','branch','subbranch','cluster_sales','provinsi','kabupaten','kecamatan','kelurahan','negotiated_qos','requested_qos','subscribed_qos','dialled_apn','event_type','provider_id','currency','subscriber_status','forwarding_flag','first_call_flag','camel_roaming','time_zone','account_balance','account_number','event_source','guiding_resource_type','rounded_duration','total_volume','rounded_total_volume','event_start_period','cifa','account_delta','bonus_consumed','credit_indicator','rev','discount_amount','free_total_volume','free_duration','call_direction','charge_code','special_number_ind','bonus_information','internal_cause','basic_cause','time_band','call_type','vas_code','service_filter','national_calling_zone','national_called_zone','international_calling_zone','international_called_zone','event_id','access_code','country_name','cp_name','content_id','rating_group','bft_indicator','unapplied_amount','partition_id','rated_date_time','area','cost_band','l4_name','l3_name','l2_name','l1_name','rating_offer_id','settlement_indicator','tap_code','mcc_mnc','rating_pricing_item_id','file_identifier','record_number','future_string1','future_string2','future_string3','allowance_consumed_revenue','ifrs_ind_for_allowance_revenue','ifrs_ind_for_vas_event','itemized_bill_fee','consumed_monetary_allowance','partial_charge_ind','brand','offer_id','file_id','load_ts','load_user','site_name','pre_post_flag','mcc','mnc','network_activity_id','filename','rec_id','event_date','productline_bonus_l4','retry_count','retry_ts','status_data','status','trx_lacci')

# PROSES REJECT service_filter
df_ServiceFilter_reject = df_FilterR.withColumn('l4_name', lit("NQ"))\
                                    .withColumn('l3_name', lit("NQ"))\
                                    .withColumn('l2_name', lit("NQ"))\
                                    .withColumn('l1_name', lit("NQ"))\
                                    .select('timestamp_r','trx_date','trx_hour','a_party','account_owner','msisdn','subs_id','cust_type_desc','cust_subtype_desc','location_number_type_a','location_number_a','b_party','location_number_type_b','location_number_b','number_of_reroutings','imsi','number_of_network_reroutings','redirecting_party_id','pre_call_duration','call_duration','chargingid','roaming_flag','vlr_num','cell_id','lacci_id','lacci_closing_flag','lac','ci','node_type','area_sales','region_sales','branch','subbranch','cluster_sales','provinsi','kabupaten','kecamatan','kelurahan','negotiated_qos','requested_qos','subscribed_qos','dialled_apn','event_type','provider_id','currency','subscriber_status','forwarding_flag','first_call_flag','camel_roaming','time_zone','account_balance','account_number','event_source','guiding_resource_type','rounded_duration','total_volume','rounded_total_volume','event_start_period','cifa','account_delta','bonus_consumed','credit_indicator','rev','discount_amount','free_total_volume','free_duration','call_direction','charge_code','special_number_ind','bonus_information','internal_cause','basic_cause','time_band','call_type','vas_code','service_filter','national_calling_zone','national_called_zone','international_calling_zone','international_called_zone','event_id','access_code','country_name','cp_name','content_id','rating_group','bft_indicator','unapplied_amount','partition_id','rated_date_time','area','cost_band','l4_name','l3_name','l2_name','l1_name','rating_offer_id','settlement_indicator','tap_code','mcc_mnc','rating_pricing_item_id','file_identifier','record_number','future_string1','future_string2','future_string3','allowance_consumed_revenue','ifrs_ind_for_allowance_revenue','ifrs_ind_for_vas_event','itemized_bill_fee','consumed_monetary_allowance','partial_charge_ind','brand','offer_id','file_id','load_ts','load_user','site_name','pre_post_flag','mcc','mnc','network_activity_id','filename','rec_id','event_date','productline_bonus_l4','retry_count','retry_ts','status_data','status','trx_lacci')

# CEK
print("S1=", df_ServiceFilter1.count(),"S2=", df_ServiceFilter2.count(),"S3=", df_ServiceFilter3.count(),"S5=", df_ServiceFilter5.count(),"R=", df_ServiceFilter_reject.count())


# MERGE & ranking
window = Window.partitionBy('key_timestap_r','key_a_party','key_b_party','key_call_duration','key_charging_id','key_total_volume','key_account_delta','key_bonus_consumed').orderBy('filename','rec_id')
df = [ df_ServiceFilter1, df_ServiceFilter2, df_ServiceFilter3, df_ServiceFilter5, df_ServiceFilter_reject ]
dfJOINprodline = reduce(DataFrame.unionAll, df)\
                .withColumn('substr_offerid', substring((trim(col('offer_id'))), 3,8))\
                .join(df_SAProdline,col('substr_offerid') == col('substr_l4'), how = 'left')\
                .withColumn('productline_bonus_l4', 
                        F.when((F.col('substr_offerid') == F.col('substr_l4')), F.col('l4'))
                            .otherwise(""))\
                .withColumn('key_b_party', 
                        F.when(F.col('service_filter').like("%GPRS%"), "")
                            .otherwise(F.col('b_party')))\
                .withColumn('key_call_duration', 
                        F.when(F.col('service_filter').like("%GPRS%"), "0")
                            .otherwise(F.col('call_duration')))\
                .withColumn('key_charging_id', 
                        F.when(F.col('service_filter').like("%GPRS%"), F.col('chargingid'))
                            .otherwise(""))\
                .withColumn('key_total_volume', 
                        F.when(F.col('service_filter').like("%GPRS%"), F.col('total_volume'))
                            .otherwise("0"))\
                .select('timestamp_r','trx_date','trx_hour','a_party','account_owner','msisdn','subs_id','cust_type_desc','cust_subtype_desc','location_number_type_a','location_number_a','b_party','location_number_type_b','location_number_b','number_of_reroutings','imsi','number_of_network_reroutings','redirecting_party_id','pre_call_duration','call_duration','chargingid','roaming_flag','vlr_num','cell_id','lacci_id','lacci_closing_flag','lac','ci','node_type','area_sales','region_sales','branch','subbranch','cluster_sales','provinsi','kabupaten','kecamatan','kelurahan','negotiated_qos','requested_qos','subscribed_qos','dialled_apn','event_type','provider_id','currency','subscriber_status','forwarding_flag','first_call_flag','camel_roaming','time_zone','account_balance','account_number','event_source','guiding_resource_type','rounded_duration','total_volume','rounded_total_volume','event_start_period','cifa','account_delta','bonus_consumed','credit_indicator','rev','discount_amount','free_total_volume','free_duration','call_direction','charge_code','special_number_ind','bonus_information','internal_cause','basic_cause','time_band','call_type','vas_code','service_filter','national_calling_zone','national_called_zone','international_calling_zone','international_called_zone','event_id','access_code','country_name','cp_name','content_id','rating_group','bft_indicator','unapplied_amount','partition_id','rated_date_time','area','cost_band','l4_name','l3_name','l2_name','l1_name','rating_offer_id','settlement_indicator','tap_code','mcc_mnc','rating_pricing_item_id','file_identifier','record_number','future_string1','future_string2','future_string3','allowance_consumed_revenue','ifrs_ind_for_allowance_revenue','ifrs_ind_for_vas_event','itemized_bill_fee','consumed_monetary_allowance','partial_charge_ind','brand','offer_id','file_id','load_ts','load_user','site_name','pre_post_flag','mcc','mnc','network_activity_id','filename','rec_id','event_date','productline_bonus_l4','retry_count','retry_ts','status_data','status','trx_lacci','timestamp_r','a_party','key_b_party','key_call_duration','key_charging_id','key_total_volume','account_delta','bonus_consumed')\
                .toDF('timestamp_r','trx_date','trx_hour','a_party','account_owner','msisdn','subs_id','cust_type_desc','cust_subtype_desc','location_number_type_a','location_number_a','b_party','location_number_type_b','location_number_b','number_of_reroutings','imsi','number_of_network_reroutings','redirecting_party_id','pre_call_duration','call_duration','chargingid','roaming_flag','vlr_num','cell_id','lacci_id','lacci_closing_flag','lac','ci','node_type','area_sales','region_sales','branch','subbranch','cluster_sales','provinsi','kabupaten','kecamatan','kelurahan','negotiated_qos','requested_qos','subscribed_qos','dialled_apn','event_type','provider_id','currency','subscriber_status','forwarding_flag','first_call_flag','camel_roaming','time_zone','account_balance','account_number','event_source','guiding_resource_type','rounded_duration','total_volume','rounded_total_volume','event_start_period','cifa','account_delta','bonus_consumed','credit_indicator','rev','discount_amount','free_total_volume','free_duration','call_direction','charge_code','special_number_ind','bonus_information','internal_cause','basic_cause','time_band','call_type','vas_code','service_filter','national_calling_zone','national_called_zone','international_calling_zone','international_called_zone','event_id','access_code','country_name','cp_name','content_id','rating_group','bft_indicator','unapplied_amount','partition_id','rated_date_time','area','cost_band','l4_name','l3_name','l2_name','l1_name','rating_offer_id','settlement_indicator','tap_code','mcc_mnc','rating_pricing_item_id','file_identifier','record_number','future_string1','future_string2','future_string3','allowance_consumed_revenue','ifrs_ind_for_allowance_revenue','ifrs_ind_for_vas_event','itemized_bill_fee','consumed_monetary_allowance','partial_charge_ind','brand','offer_id','file_id','load_ts','load_user','site_name','pre_post_flag','mcc','mnc','network_activity_id','filename','rec_id','event_date','productline_bonus_l4','retry_count','retry_ts','status_data','status','trx_lacci','key_timestap_r','key_a_party','key_b_party','key_call_duration','key_charging_id','key_total_volume','key_account_delta','key_bonus_consumed')\
                .withColumn("ranking", dense_rank().over(window))

# SPLIT FILTER
dfCEKdup = dfJOINprodline.filter(col('ranking')  == 1)\
                .withColumn('status_data',
                            F.when((col('subs_id').isNull()) | (trim(col('subs_id')) == "") | (col('subs_id') == "-99")\
                                    | (col('cust_type_desc').isNull()) | (trim(col('cust_type_desc')) == "") | (col('cust_type_desc') == "-99")\
                                    | (col('lacci_id').isNull()) | (trim(col('lacci_id')) == "") | (col('lacci_id') == "-99")\
                                    | (col('lacci_closing_flag').isNull()) | (trim(col('lacci_closing_flag')) == "") | (col('lacci_closing_flag') == "-1")\
                                    | (col('lac').isNull()) | (trim(col('lac')) == "") | (col('lac') == "NQ")\
                                    | (col('ci').isNull()) | (trim(col('ci')) == "") | (col('ci') == "NQ")\
                                    | (col('node_type').isNull()) | (trim(col('node_type')) == "") | (col('node_type') == "NQ")\
                                    | (col('area_sales').isNull()) | (trim(col('area_sales')) == "") | (col('area_sales') == "NQ")\
                                    | (col('region_sales').isNull()) | (trim(col('region_sales')) == "") | (col('region_sales') == "NQ")\
                                    | (col('branch').isNull()) | (trim(col('branch')) == "") | (col('branch') == "NQ")\
                                    | (col('subbranch').isNull()) | (trim(col('subbranch')) == "") | (col('subbranch') == "NQ")\
                                    | (col('cluster_sales').isNull()) | (trim(col('cluster_sales')) == "") | (col('cluster_sales') == "NQ")\
                                    | (col('provinsi').isNull()) | (trim(col('provinsi')) == "") | (col('provinsi') == "NQ")\
                                    | (col('kabupaten').isNull()) | (trim(col('kabupaten')) == "") | (col('kabupaten') == "NQ")\
                                    | (col('kecamatan').isNull()) | (trim(col('kecamatan')) == "") | (col('kecamatan') == "NQ")\
                                    | (col('kelurahan').isNull()) | (trim(col('kelurahan')) == "") | (col('kelurahan') == "NQ")\
                                    | (col('l4_name').isNull()) | (trim(col('l4_name')) == "") | (col('l4_name') == "NQ")\
                                    | (col('l3_name').isNull()) | (trim(col('l3_name')) == "") | (col('l3_name') == "NQ")\
                                    | (col('l2_name').isNull()) | (trim(col('l2_name')) == "") | (col('l2_name') == "NQ")\
                                    | (col('l1_name').isNull()) | (trim(col('l1_name')) == "") | (col('l1_name') == "NQ"),'REJECT')
                                .otherwise('GOOD'))\
                .withColumn('status', 
                              F.when(F.col('status') == "DUP", F.col('status'))
                                  .otherwise("NODUP"))\
                .select('timestamp_r','trx_date','trx_hour','a_party','account_owner','msisdn','subs_id','cust_type_desc','cust_subtype_desc','location_number_type_a','location_number_a','b_party','location_number_type_b','location_number_b','number_of_reroutings','imsi','number_of_network_reroutings','redirecting_party_id','pre_call_duration','call_duration','chargingid','roaming_flag','vlr_num','cell_id','lacci_id','lacci_closing_flag','lac','ci','node_type','area_sales','region_sales','branch','subbranch','cluster_sales','provinsi','kabupaten','kecamatan','kelurahan','negotiated_qos','requested_qos','subscribed_qos','dialled_apn','event_type','provider_id','currency','subscriber_status','forwarding_flag','first_call_flag','camel_roaming','time_zone','account_balance','account_number','event_source','guiding_resource_type','rounded_duration','total_volume','rounded_total_volume','event_start_period','cifa','account_delta','bonus_consumed','credit_indicator','rev','discount_amount','free_total_volume','free_duration','call_direction','charge_code','special_number_ind','bonus_information','internal_cause','basic_cause','time_band','call_type','vas_code','service_filter','national_calling_zone','national_called_zone','international_calling_zone','international_called_zone','event_id','access_code','country_name','cp_name','content_id','rating_group','bft_indicator','unapplied_amount','partition_id','rated_date_time','area','cost_band','l4_name','l3_name','l2_name','l1_name','rating_offer_id','settlement_indicator','tap_code','mcc_mnc','rating_pricing_item_id','file_identifier','record_number','future_string1','future_string2','future_string3','allowance_consumed_revenue','ifrs_ind_for_allowance_revenue','ifrs_ind_for_vas_event','itemized_bill_fee','consumed_monetary_allowance','partial_charge_ind','brand','offer_id','file_id','load_ts','load_user','site_name','pre_post_flag','mcc','mnc','network_activity_id','filename','rec_id','event_date','productline_bonus_l4','retry_count','retry_ts','status_data','status','ranking','trx_lacci')

# SPLIT FILTER
dfREJECT = dfCEKdup.filter(col('status_data')  == 'REJECT').withColumn('load_date', lit("20230120"))\
                .select('timestamp_r','trx_date','trx_hour','a_party','account_owner','msisdn','subs_id','cust_type_desc','cust_subtype_desc','location_number_type_a','location_number_a','b_party','location_number_type_b','location_number_b','number_of_reroutings','imsi','number_of_network_reroutings','redirecting_party_id','pre_call_duration','call_duration','chargingid','roaming_flag','vlr_num','cell_id','lacci_id','lacci_closing_flag','lac','ci','node_type','area_sales','region_sales','branch','subbranch','cluster_sales','provinsi','kabupaten','kecamatan','kelurahan','negotiated_qos','requested_qos','subscribed_qos','dialled_apn','event_type','provider_id','currency','subscriber_status','forwarding_flag','first_call_flag','camel_roaming','time_zone','account_balance','account_number','event_source','guiding_resource_type','rounded_duration','total_volume','rounded_total_volume','event_start_period','cifa','account_delta','bonus_consumed','credit_indicator','rev','discount_amount','free_total_volume','free_duration','call_direction','charge_code','special_number_ind','bonus_information','internal_cause','basic_cause','time_band','call_type','vas_code','service_filter','national_calling_zone','national_called_zone','international_calling_zone','international_called_zone','event_id','access_code','country_name','cp_name','content_id','rating_group','bft_indicator','unapplied_amount','partition_id','rated_date_time','area','cost_band','l4_name','l3_name','l2_name','l1_name','rating_offer_id','settlement_indicator','tap_code','mcc_mnc','rating_pricing_item_id','file_identifier','record_number','future_string1','future_string2','future_string3','allowance_consumed_revenue','ifrs_ind_for_allowance_revenue','ifrs_ind_for_vas_event','itemized_bill_fee','consumed_monetary_allowance','partial_charge_ind','brand','offer_id','file_id','load_ts','load_user','site_name','pre_post_flag','mcc','mnc','network_activity_id','event_date','productline_bonus_l4','filename','rec_id','retry_count','retry_ts','event_date','load_date')\
                .toDF('timestamp_r','trx_date','trx_hour','a_party','account_owner','msisdn','subs_id','cust_type_desc','cust_subtype_desc','location_number_type_a','location_number_a','b_party','location_number_type_b','location_number_b','number_of_reroutings','imsi','number_of_network_reroutings','redirecting_party_id','pre_call_duration','call_duration','chargingid','roaming_flag','vlr_num','cell_id','lacci_id','lacci_closing_flag','lac','ci','node_type','area_sales','region_sales','branch','subbranch','cluster_sales','provinsi','kabupaten','kecamatan','kelurahan','negotiated_qos','requested_qos','subscribed_qos','dialled_apn','event_type','provider_id','currency','subscriber_status','forwarding_flag','first_call_flag','camel_roaming','time_zone','account_balance','account_number','event_source','guiding_resource_type','rounded_duration','total_volume','rounded_total_volume','event_start_period','cifa','account_delta','bonus_consumed','credit_indicator','rev','discount_amount','free_total_volume','free_duration','call_direction','charge_code','special_number_ind','bonus_information','internal_cause','basic_cause','time_band','call_type','vas_code','service_filter','national_calling_zone','national_called_zone','international_calling_zone','international_called_zone','event_id','access_code','country_name','cp_name','content_id','rating_group','bft_indicator','unapplied_amount','partition_id','rated_date_time','area','cost_band','l4_name','l3_name','l2_name','l1_name','rating_offer_id','settlement_indicator','tap_code','mcc_mnc','rating_pricing_item_id','file_identifier','record_number','future_string1','future_string2','future_string3','allowance_consumed_revenue','ifrs_ind_for_allowance_revenue','ifrs_ind_for_vas_event','itemized_bill_fee','consumed_monetary_allowance','partial_charge_ind','brand','offer_id','file_id','load_ts','load_user','site_name','pre_post_flag','mcc','mnc','network_activity_id','event_date','productline_bonus_l4','filename','rec_id','retry_count','retry_ts','p_event_date','load_date')

dfGOOD = dfCEKdup.filter(col('status_data')  == 'GOOD').withColumn('load_date', lit("20230120"))\
                .select('timestamp_r','trx_date','trx_hour','a_party','account_owner','msisdn','subs_id','cust_type_desc','cust_subtype_desc','location_number_type_a','location_number_a','b_party','location_number_type_b','location_number_b','number_of_reroutings','imsi','number_of_network_reroutings','redirecting_party_id','pre_call_duration','call_duration','chargingid','roaming_flag','vlr_num','cell_id','lacci_id','lacci_closing_flag','lac','ci','node_type','area_sales','region_sales','branch','subbranch','cluster_sales','provinsi','kabupaten','kecamatan','kelurahan','negotiated_qos','requested_qos','subscribed_qos','dialled_apn','event_type','provider_id','currency','subscriber_status','forwarding_flag','first_call_flag','camel_roaming','time_zone','account_balance','account_number','event_source','guiding_resource_type','rounded_duration','total_volume','rounded_total_volume','event_start_period','cifa','account_delta','bonus_consumed','credit_indicator','rev','discount_amount','free_total_volume','free_duration','call_direction','charge_code','special_number_ind','bonus_information','internal_cause','basic_cause','time_band','call_type','vas_code','service_filter','national_calling_zone','national_called_zone','international_calling_zone','international_called_zone','event_id','access_code','country_name','cp_name','content_id','rating_group','bft_indicator','unapplied_amount','partition_id','rated_date_time','area','cost_band','l4_name','l3_name','l2_name','l1_name','rating_offer_id','settlement_indicator','tap_code','mcc_mnc','rating_pricing_item_id','file_identifier','record_number','future_string1','future_string2','future_string3','allowance_consumed_revenue','ifrs_ind_for_allowance_revenue','ifrs_ind_for_vas_event','itemized_bill_fee','consumed_monetary_allowance','partial_charge_ind','brand','offer_id','file_id','load_ts','load_user','site_name','pre_post_flag','mcc','mnc','network_activity_id','event_date','productline_bonus_l4','filename','rec_id','retry_count','retry_ts','event_date','load_date')\
                .toDF('timestamp_r','trx_date','trx_hour','a_party','account_owner','msisdn','subs_id','cust_type_desc','cust_subtype_desc','location_number_type_a','location_number_a','b_party','location_number_type_b','location_number_b','number_of_reroutings','imsi','number_of_network_reroutings','redirecting_party_id','pre_call_duration','call_duration','chargingid','roaming_flag','vlr_num','cell_id','lacci_id','lacci_closing_flag','lac','ci','node_type','area_sales','region_sales','branch','subbranch','cluster_sales','provinsi','kabupaten','kecamatan','kelurahan','negotiated_qos','requested_qos','subscribed_qos','dialled_apn','event_type','provider_id','currency','subscriber_status','forwarding_flag','first_call_flag','camel_roaming','time_zone','account_balance','account_number','event_source','guiding_resource_type','rounded_duration','total_volume','rounded_total_volume','event_start_period','cifa','account_delta','bonus_consumed','credit_indicator','rev','discount_amount','free_total_volume','free_duration','call_direction','charge_code','special_number_ind','bonus_information','internal_cause','basic_cause','time_band','call_type','vas_code','service_filter','national_calling_zone','national_called_zone','international_calling_zone','international_called_zone','event_id','access_code','country_name','cp_name','content_id','rating_group','bft_indicator','unapplied_amount','partition_id','rated_date_time','area','cost_band','l4_name','l3_name','l2_name','l1_name','rating_offer_id','settlement_indicator','tap_code','mcc_mnc','rating_pricing_item_id','file_identifier','record_number','future_string1','future_string2','future_string3','allowance_consumed_revenue','ifrs_ind_for_allowance_revenue','ifrs_ind_for_vas_event','itemized_bill_fee','consumed_monetary_allowance','partial_charge_ind','brand','offer_id','file_id','load_ts','load_user','site_name','pre_post_flag','mcc','mnc','network_activity_id','event_date','productline_bonus_l4','filename','rec_id','retry_count','retry_ts','p_event_date','load_date')

# FILTER
window = Window.partitionBy('rec_id','event_date').orderBy('timestamp_r','trx_date','trx_hour','a_party','account_owner','msisdn','subs_id','cust_type_desc','cust_subtype_desc','location_number_type_a','location_number_a','b_party','location_number_b','number_of_reroutings','location_number_type_b','imsi','number_of_network_reroutings','pre_call_duration','redirecting_party_id','call_duration','chargingid','roaming_flag','vlr_num','cell_id','lacci_id','lacci_closing_flag','lac','ci','node_type','area_sales','region_sales','branch','subbranch','cluster_sales','provinsi','kabupaten','kecamatan','kelurahan','negotiated_qos','requested_qos','subscribed_qos','dialled_apn','event_type','provider_id','currency','subscriber_status','forwarding_flag','first_call_flag','camel_roaming','time_zone','account_balance','account_number','event_source','guiding_resource_type','rounded_duration','total_volume','rounded_total_volume','event_start_period','cifa','account_delta','bonus_consumed','credit_indicator','discount_amount','rev','free_duration','free_total_volume','call_direction','charge_code','special_number_ind','bonus_information','internal_cause','basic_cause','time_band','call_type','vas_code','service_filter','national_calling_zone','national_called_zone','international_calling_zone','international_called_zone','event_id','access_code','country_name','cp_name','content_id','rating_group','bft_indicator','unapplied_amount','partition_id','rated_date_time','area','cost_band','l4_name','l3_name','l2_name','l1_name','rating_offer_id','settlement_indicator','tap_code','mcc_mnc','rating_pricing_item_id','file_identifier','record_number','future_string1','future_string2','future_string3','allowance_consumed_revenue','ifrs_ind_for_allowance_revenue','ifrs_ind_for_vas_event','itemized_bill_fee','consumed_monetary_allowance','partial_charge_ind','brand','offer_id','file_id','load_ts','load_user','site_name','pre_post_flag','mcc','mnc','network_activity_id','filename','rec_id','event_date','productline_bonus_l4','retry_count','retry_ts','status_data','status')
dfCEKdup2 = dfJOINprodline.filter(col('ranking')  != 1)
dfCEKdup2 = dfCEKdup2.withColumn('status_data',
                            F.when((col('subs_id').isNull()) | (trim(col('subs_id')) == "") | (col('subs_id') == "-99")\
                                    | (col('cust_type_desc').isNull()) | (trim(col('cust_type_desc')) == "") | (col('cust_type_desc') == "-99")\
                                    | (col('lacci_id').isNull()) | (trim(col('lacci_id')) == "") | (col('lacci_id') == "-99")\
                                    | (col('lacci_closing_flag').isNull()) | (trim(col('lacci_closing_flag')) == "") | (col('lacci_closing_flag') == "-1")\
                                    | (col('lac').isNull()) | (trim(col('lac')) == "") | (col('lac') == "NQ")\
                                    | (col('ci').isNull()) | (trim(col('ci')) == "") | (col('ci') == "NQ")\
                                    | (col('node_type').isNull()) | (trim(col('node_type')) == "") | (col('node_type') == "NQ")\
                                    | (col('area_sales').isNull()) | (trim(col('area_sales')) == "") | (col('area_sales') == "NQ")\
                                    | (col('region_sales').isNull()) | (trim(col('region_sales')) == "") | (col('region_sales') == "NQ")\
                                    | (col('branch').isNull()) | (trim(col('branch')) == "") | (col('branch') == "NQ")\
                                    | (col('subbranch').isNull()) | (trim(col('subbranch')) == "") | (col('subbranch') == "NQ")\
                                    | (col('cluster_sales').isNull()) | (trim(col('cluster_sales')) == "") | (col('cluster_sales') == "NQ")\
                                    | (col('provinsi').isNull()) | (trim(col('provinsi')) == "") | (col('provinsi') == "NQ")\
                                    | (col('kabupaten').isNull()) | (trim(col('kabupaten')) == "") | (col('kabupaten') == "NQ")\
                                    | (col('kecamatan').isNull()) | (trim(col('kecamatan')) == "") | (col('kecamatan') == "NQ")\
                                    | (col('kelurahan').isNull()) | (trim(col('kelurahan')) == "") | (col('kelurahan') == "NQ")\
                                    | (col('l4_name').isNull()) | (trim(col('l4_name')) == "") | (col('l4_name') == "NQ")\
                                    | (col('l3_name').isNull()) | (trim(col('l3_name')) == "") | (col('l3_name') == "NQ")\
                                    | (col('l2_name').isNull()) | (trim(col('l2_name')) == "") | (col('l2_name') == "NQ")\
                                    | (col('l1_name').isNull()) | (trim(col('l1_name')) == "") | (col('l1_name') == "NQ"),'REJECT')
                                .otherwise('GOOD'))\
                    .withColumn("RANKING", dense_rank().over(window))\
                    .select('timestamp_r','trx_date','trx_hour','a_party','account_owner','msisdn','subs_id','cust_type_desc','cust_subtype_desc','location_number_type_a','location_number_a','b_party','location_number_type_b','location_number_b','number_of_reroutings','imsi','number_of_network_reroutings','redirecting_party_id','pre_call_duration','call_duration','chargingid','roaming_flag','vlr_num','cell_id','lacci_id','lacci_closing_flag','lac','ci','node_type','area_sales','region_sales','branch','subbranch','cluster_sales','provinsi','kabupaten','kecamatan','kelurahan','negotiated_qos','requested_qos','subscribed_qos','dialled_apn','event_type','provider_id','currency','subscriber_status','forwarding_flag','first_call_flag','camel_roaming','time_zone','account_balance','account_number','event_source','guiding_resource_type','rounded_duration','total_volume','rounded_total_volume','event_start_period','cifa','account_delta','bonus_consumed','credit_indicator','rev','discount_amount','free_total_volume','free_duration','call_direction','charge_code','special_number_ind','bonus_information','internal_cause','basic_cause','time_band','call_type','vas_code','service_filter','national_calling_zone','national_called_zone','international_calling_zone','international_called_zone','event_id','access_code','country_name','cp_name','content_id','rating_group','bft_indicator','unapplied_amount','partition_id','rated_date_time','area','cost_band','l4_name','l3_name','l2_name','l1_name','rating_offer_id','settlement_indicator','tap_code','mcc_mnc','rating_pricing_item_id','file_identifier','record_number','future_string1','future_string2','future_string3','allowance_consumed_revenue','ifrs_ind_for_allowance_revenue','ifrs_ind_for_vas_event','itemized_bill_fee','consumed_monetary_allowance','partial_charge_ind','brand','offer_id','file_id','load_ts','load_user','site_name','pre_post_flag','mcc','mnc','network_activity_id','filename','rec_id','event_date','productline_bonus_l4','retry_count','retry_ts','status_data','status','RANKING')

# SA_USAGE_CHG AGG
df_AGG = dfCEKdup.select('event_date','filename','status_data','status','rev')\
                 .withColumn('job_id', lit("20230206151400"))\
                 .withColumn('group_process', lit("1"))\
                 .withColumn('qty', lit("1"))\
                 .withColumn('filetype', lit("SA_USAGE_OCS_CHG"))\
                 .withColumn('periode', F.regexp_replace('event_date', r'^-^', ''))\
                 .groupby(['periode','filename','job_id','group_process','status_data','status','filetype']).agg(count('qty').alias("qty"), sum('rev').alias("rev"))\
                 .select('periode','filename','job_id','group_process','status_data','status','qty','rev','filetype')


# CEK
# dfJOINprodline.select('ranking').distinct().show()
#dfJOINprodline.where("substr_offerid == substr_l4").show()
print("Total row hasil GOOD=",dfGOOD.count()," dan hasil REJECT=", dfREJECT.count(), " hasil dup=", dfCEKdup2.count())

# WRITE SA_PAYR GOOD and REJECT to csv
dfGOOD.write.mode('overwrite').saveAsTable("output.hasilSA_USAGE_CHG_GOODr")
dfREJECT.write.mode('overwrite').saveAsTable("output.hasilSA_USAGE_CHG_REJECT")
dfCEKdup2.write.mode('overwrite').saveAsTable("output.hasilSA_USAGE_CHG_DUP02")
df_AGG.write.mode('overwrite').saveAsTable("output.hasilSA_USAGE_CHG_SUM")

end_date = datetime.today() + timedelta(hours=7)
duration = (end_date - start_date)
print("start date:",start_date," end date:",end_date," duration:",duration)

# CREATE FILELOG
app = "chg_hive2"
nama_file = "/home/hdoop/BelajarPyspark/"+app+"_"+run_date+".log"
f = open(nama_file, "w")
f.writelines('\nSTART_DATE={}'.format(start_date.strftime('%Y-%m-%d %H:%M:%S')))
f.writelines('\nEND_DATE={}'.format(end_date.strftime('%Y-%m-%d %H:%M:%S')))
f.writelines('\nDURATION={}'.format(duration))
f.close()